### ISSUE TITLE
Deleting a single field from Firestore Document doesn't update the MeiliSearch record

### ISSUE THREAD

**Issue by yamankatby** [meilisearch/firestore-meilisearch#103]
**Description**
Deleting a single field from Firestore Document doesn't update the MeiliSearch record

**Expected behavior**
Delete the field from the MeiliSearch record

**Current behavior**
nothing happening, no unusual log

**Screenshots or Logs**
![Screen Shot 2022-09-01 at 13 51 10](https://user-images.githubusercontent.com/35961879/188451183-7b8961f2-6a92-479a-94f2-7b2d834e53d1.png)

**Environment (please complete the following information):**
- OS: [e.g. Debian GNU/Linux]
- Meilisearch version: [e.g. v.0.20.0]
- firestore-meilisearch version: [e.g v0.1.0]

**Comment by bidoubiwa** [comment]
Hey @yamankatby 
Thanks for raising this, I will look into it :)

**Comment by bidoubiwa** [comment]
Hey @yamankatby 
I tried to reproduce the error but I couldn't manage to do so: 


```
// Create document with field `hello: 1`
>  {"_firestore_id":"IUq1HiuPA3j4bE8NjcHe","hello":"1","severity":"INFO","message":"Creating new document IUq1HiuPA3j4bE8NjcHe in Meilisearch index movies"}

// Update same document with field `hello: 2`
>  {"_firestore_id":"IUq1HiuPA3j4bE8NjcHe","hello":"2","severity":"INFO","message":"Updating document IUq1HiuPA3j4bE8NjcHe in Meilisearch index movies"}

// Update same document by removing the field `hello`
>  {"_firestore_id":"IUq1HiuPA3j4bE8NjcHe","severity":"INFO","message":"Updating document IUq1HiuPA3j4bE8NjcHe in Meilisearch index movies"}
```

**Comment by yamankatby** [comment]
Hi @bidoubiwa, Thank you for your response.
As I remember, I had the same response in the tasks API, but the MeiliSearch record didn't change.

**Comment by bidoubiwa** [comment]
Oh! I will check that! 

I'm on holidays next week, I'll come back to you the week after :)

**Comment by bidoubiwa** [comment]
Hey @yamankatby 
I just tried again, it did remove the document from Meilisearch as well.
Do you remember how your document was formatted?
