### ISSUE TITLE
Reference the tasks API in the monitoring section in the POSTINSTALL

### ISSUE THREAD

**Issue by yamankatby** [meilisearch/firestore-meilisearch#108]
**Description**
As errors will not be displayed on the functions logs page, it will be good to mention the tasks API and the mailisearch dashboard as a monitoring resources in the POSTINSTALL

![Screen Shot 2022-09-08 at 13 34 32](https://user-images.githubusercontent.com/35961879/189101976-c3fdff33-0ee0-4c78-8c6c-16e00641f419.png)

**Comment by bidoubiwa** [comment]
Thanks! Good idea
