### ISSUE TITLE
Changing the value of a boolean in a firestore document does not always result in a document update

### ISSUE THREAD

**Issue by JQrdan** [meilisearch/firestore-meilisearch#112]
Sometimes, when a boolean attribute is flipped in a document, there is no result document update in meilisearch. In our use case we have an 'approved' attribute which decides if a document entry should be listed or not. Sometimes we toggle the approve attribute on these documents and they remain in our list of 'un-approved' items as the meilisearch document has not been updated but the firebase document has

Environment:
- OS: Debian GNU/Linux 
- Meilisearch version: 0.28.0
- firestore-meilisearch version: 0.1.5

**Comment by bidoubiwa** [comment]
Hey @JQrdan 
Sorry for the delay in my answer! I will look into this asap :)

**Comment by bidoubiwa** [comment]
Hey, I think it may be related to #103 . Once the fix is merged and published #116 it may fix your issue.

**Comment by JQrdan** [comment]
Great! Thanks for looking 😄  I shall keep an eye on that pull request and try it out once published.

**Comment by bidoubiwa** [comment]
It has been released!

**Comment by bidoubiwa** [comment]
Hey @JQrdan, did you have time to check out if this is still an issue?

**Comment by JQrdan** [comment]
We have just updated to the latest version yesterday so I'll keep an eye on it 😁 I'm happy to close this issue for now and will re-open if we find it continues
