### ISSUE TITLE
Update the readme's with the new extension link to the marketplace

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/firestore-meilisearch#130]
**Description**
Previously we were not added in the official Marketplace of firebase. Which is the case today.
In our README we still point to the old URL: `https://console.firebase.google.com/project/_/extensions/install?ref=meilisearch/firestore-meilisearch`. This should be changed with the following link `https://extensions.dev/extensions/meilisearch/firestore-meilisearch`

The link may be present in other files than the `README.md`. Please check.

**Comment by Pragya2056** [comment]
Please assign me to this

**Comment by bidoubiwa** [comment]
Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

We prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the real volunteers contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/README.md). 

We are looking forward to reviewing your PR 😊

**Comment by Pragya2056** [comment]
#132 
The issue was  worked on.
