### ISSUE TITLE
Fix geosearch link in documentation

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/firestore-meilisearch#131]
**Description**
The link to the geosearch documentation is wrongly formatted markdown.

example:
https://github.com/meilisearch/firestore-meilisearch/blob/1681f4c6138a0e34c9aba09292709a1f10d44247/PREINSTALL.md?plain=1#L20

**Expected behavior**
It should be a working link

**Comment by ahmed-sudani** [comment]
I would like to handle this one
