### ISSUE TITLE
Meilisearch name not displayed on marketplace

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/firestore-meilisearch#138]
I looked for search extensions (https://extensions.dev/extensions?category=search) and noticed the Meiliseatch extension description is too long and gets cropped, which results in Meilisearch's name not being displayed in the title:
![Capture d’écran 2022-10-24 à 12 23 18](https://user-images.githubusercontent.com/48251481/197507939-eadcb37d-c5fd-4f4b-a9ce-4138913aef75.png)

Maybe consider removing the "in your Firestore" part.

**Comment by bidoubiwa** [comment]
Thanks @CaroFG for raising this issue :)

**Comment by gauravagrwal** [comment]
Hi @bidoubiwa, I would like to fix this, can you please assign it to me ?

**Comment by bidoubiwa** [comment]
`Search with Meilisearch` is better :) Thanks for asking
