### ISSUE TITLE
Meilisearch _geo consitency with with Firestore Geopoint

### ISSUE THREAD

**Issue by baek-b** [meilisearch/firestore-meilisearch#143]
For _geoRadius to work, the current documentation and workings of Meilisearch requires Geopoint fields in firestore to be renamed as _geo. However, when it comes to the "lat" & "lng" field name formats. Firestore does not allow renaming of these fields. These fields are named "_latitude" & "_longitude" respectively by Firestore. I was unable to do a _geoRadius search on Meiliesearch. 

Steps to reproduce the issue: 

1. Install Meilisearch on GCP   - [long story short, it works]
2. Create new index and add "_geo" to "filterableAttributes" settings -  [Works]
3. Install Meilisearch Firestore extension. [Search queries return correct results, including "_geo" fields but with "_latitude" & "_longitude". - [Works]
4. Add test documents with _geo in Firestore. - [Works]
5. Run empty q search without filter - [Works]
6. Run empty q search with {"filter": "_geoRadius( <latitude>, <longitude>, <radius in meters>)"} - [No results returned]

No results returned even if same value as the document are passed. I don't know if it's because Meilisearch is looking for "lat" & "lng" and can't find anything or something else. Either way, I could find any issues or documentation on this. 

I also came across [this](https://github.com/meilisearch/firestore-meilisearch/issues/16) issue. I'm not sure if anything has been rewritten but the documentation is not update in that case.

**Comment by baek-b** [comment]
So there is an error in the documentation for the firestore repo. It states 

> If you are using GeoPoint, the field should be named _geo to be recognized by Meilisearch for [geosearch](https://docs.meilisearch.com/reference/features/geosearch.html#geosearch).

This compeletely overlooks the fact that firestore doesn't support naming the Latitude and Longitude fields which renders using geopoint for Meilisearch useless. 

The way I got this to work is to use a map on firestore with the expected format. i.e. 

`"_geo": {
    "lat": 0.0,
    "lng": "0.0"
  }`

**Comment by bidoubiwa** [comment]
Hey @baek-b 

This seems to be a bug! The fields should have been adapted

**Comment by bidoubiwa** [comment]
I made an issue on firebase side: https://github.com/googleapis/nodejs-firestore/issues/1799#issuecomment-1325283382

I'm still looking for a work-around meanwhile, I'll keep you updated :)

**Comment by bidoubiwa** [comment]
After further investigation, the error comes from my side. I will be fixing this asap!
