### ISSUE TITLE
Does not index documents that have a "." within their UID

### ISSUE THREAD

**Issue by louisifn** [meilisearch/firestore-meilisearch#157]
**Description**
I have a collection where all documents are named with their URL to avoid document duplication for domains

**Expected behaviour**
All documents to be indexed

**Current behaviour**
Only documents without a full stop/period (.) within their UID are indexed.

I am pretty sure this is just a bug and would very much like to avoid having to reformat the collection to operate with the extensions if viable - would love anyone's thoughts on this - many thanks!

**Comment by bidoubiwa** [comment]
Hey @louisifn, unfortunately Meilisearch does not accept document UID's with a `.` symbol. As per the [documentation here](https://docs.meilisearch.com/learn/core_concepts/primary_key.html#formatting-the-document-id).

> The document id must be an integer or a string. If the id is a string, it can only contain alphanumeric characters (a-z, A-Z, 0-9), hyphens (-), and underscores (_).

If you'd like that to be possible, you could open a discussion about it on our [product repository](https://github.com/meilisearch/product/discussions)! It may be that other users want this as well :)

**Comment by bidoubiwa** [comment]
Closing this as it is not related to firestore
