### ISSUE TITLE
Ignore null values on _geo search fields

### ISSUE THREAD

**Issue by oplik0** [meilisearch/firestore-meilisearch#160]
**Description**
Currently as long as field is being indexed the value will be passed to MeiliSearch. Null values are not taken into account for indexing, and in some instances can actually cause the task to fail - for example, a `_geo` field can't be set to null.

I'm not sure about the best way to handle this.

The least potentially disruptive is handling the edge cases specifically - which as far as I know is only `_geo`. However this means other nulls are still being pushed and if there are other edge cases, they might cause issues.

I don't think there would actually be any issues with not pushing null values to meilisearch at all, but perhaps someone has some use for them that I can't see?

If that's the case, perhaps a setting to enable discarding null values might be an option?

**Basic example**
See #161 for the fix with the first option - discarding invalid `_geo` values

If any of the other options would be preferred I can change that PR or make a new one with the desired changes.

**Other**
found because `firestore_odm` creates all fields from the model and just sets optional ones that aren't given a value to null...

**Comment by bidoubiwa** [comment]
Hey @oplik0!

Thanks for raising this! Since [v1.1.0 of Meilisearch](https://github.com/meilisearch/meilisearch/releases/tag/v1.1.0), `_geo` field accepts a null value

> Accept null as a valid _geo field when importing or updating documents (https://github.com/meilisearch/meilisearch/pull/3515) @irevoire


Anyway, you are right it should still work with v1.0.0!
