### ISSUE TITLE
Add a way to provide the index settings from the extension configuration panel

### ISSUE THREAD

**Issue by alallema** [meilisearch/firestore-meilisearch#35]
**Description**

Currently, the extension indexes the documents add, update or delete to `Firestore` in a `Meilisearch` instance. It could be interesting to add the possibility to make settings. There are several that we could implement like `searchableAttributes`.

**Basic example**

We could add this setting option in the extension configuration panel:

![159304851-2aba55fd-493f-4bec-b825-6a65999e636d](https://user-images.githubusercontent.com/16155041/160366649-0dc7268e-f37f-42d0-934e-77df8889043c.png)

**Comment by bidoubiwa** [comment]
To avoid overwhelming the user with to many questions, we prefer not implementing this for the moment. If asked for, we may reconsider

**Comment by bidoubiwa** [comment]
To avoid overwhelming the user with too many questions, we prefer not implementing this for the moment.
