### ISSUE TITLE
Remove `Publish with beta tag` step on `publish.yml`

### ISSUE THREAD

**Issue by alallema** [meilisearch/firestore-meilisearch#51]
The `publish.yml` file is supposed to publish the version on `NPM` after doing some checks.
For the first version, we wanted to give ourselves the possibility to publish a beta in case of problems.
In the end, we don't use this beta step so we can remove it from this file.

**Comment by bidoubiwa** [comment]
After discussion, we are keeping the possibility to create a beta version. Closing this issue
