### ISSUE TITLE
Update the firestore logs with the tasks number

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/firestore-meilisearch#74]
When an action is triggered on Meilisearch (update/create/delete document), on Meilisearch side a task is created and added in a queue.
To monitor this specific task using the [task API](https://docs.meilisearch.com/reference/api/tasks.html) the user must know the task uid. 

Since we do not provide that number in the logs, the user has to look at all the tasks to find the one they try to monitor. 
To avoid this unnecessary search, we should add the task number in the logs.

Example:
In this code: 
https://github.com/meilisearch/firestore-meilisearch/blob/a732b5462a7c14e0ed259da04e04a8bd1e1796f7/functions/src/index.ts#L68-L73

We can change the code the following way:

```js
const { taskUid } = await index.addDocuments([document], {
        primaryKey: '_firestore_id',
      })
logger.info(`The task number of the document addition is: ${taskUid}`)
```

Not sure about the logging message, tell me if you have a better idea.

**Comment by nooras** [comment]
Hi @bidoubiwa 
I am interested in this issue.
Can you please assign it to me? 

Thanks

**Comment by bidoubiwa** [comment]
Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

We prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the real volunteers contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/README.md). 

We are looking forward to reviewing your PR 😊
