### ISSUE TITLE
Add warning about using a existing `Meilisearch` index

### ISSUE THREAD

**Issue by alallema** [meilisearch/firestore-meilisearch#75]
Currently, the data format for the document is explained in the [`PREINSTALL.md` file](https://github.com/meilisearch/firestore-meilisearch/blob/main/PREINSTALL.md#data-import-format).
We should advise the users that if they want to use an existing `index` it should have `_firestore_id` as the primary Key otherwise it will not work due to primary key conflicts.
Since there is almost no chance that the primary key already inferred in the Meilisearch index is `_firestore_id` it might be nice to advice the users to not use an existing `Meilisearch` index.

**Comment by bidoubiwa** [comment]
> We should advise the users that if they want to use an existing Meilisearch it should have _firestore_id as the primary Key otherwise it will not work due to primary key conflicts.

In fact, it will work, if the user has the custom primary key in each of its documents. For example: 
```
_firebase_id: 1
product_id: 1
title: "hello"
```

If the primary key is `product_id`, when this document is added, it will succeed anyway.
