### ISSUE TITLE
Fail to publish to firestore in CI

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/firestore-meilisearch#86]
The CI should make the publishing to firestore automatically. Unfortunalty this failed. 

[See here](https://github.com/meilisearch/firestore-meilisearch/runs/6455595250?check_suite_focus=true)

the issue might come from a misunderstanding of this github action https://github.com/w9jds/firebase-action

The related action is this one: 

https://github.com/meilisearch/firestore-meilisearch/blob/192d49555c4595e987d5bf317d39a0884cd3ca6f/.github/workflows/publish.yml#L35-L53

**Comment by curquiza** [comment]
This issue seems outdated since we can now publish on npm
