### ISSUE TITLE
Indexing of multiple firestore collections

### ISSUE THREAD

**Issue by dutchkillscreative** [meilisearch/firestore-meilisearch#97]
**Description**
I'm not sure if implementation already exists, but I have two collections in my firestore I would like to track. Currently the extension is set to monitor my 'users' collection but I would also like to set up a function to track my 'photos' collection as it's also very important to index. I understand some firebase extensions allow for installation of multiple instances of the same extension to essentially repeat the process just for another configuration. My app is currently in production and I would just like confirmation if this action of initiating a second instance of the extension will not conflict with the first.

**Basic example**
I am migrating from algolia and I have two indexes I need to update through firebase, Users & Photos. Essentially when a document is created, updated, or deleted the current extension fires to update my meilisearch index. But it only tracks the single collection specified in the extension configuration. My assumption is that this is just creating a stock firebase cloud function based on the gui configuration.

I got around this limitation while using algolia by writing & deploying my own cloud functions to track the photos collection on my firestore. Obviously I can do a similar implementation but it is a bit easier to just install a second instance of the extension to configure for the other collection I want to track.

**Comment by bidoubiwa** [comment]
Hey @dutchkillscreative 

It should not conflict, unless mistaken, but I don't see why it would conflict. 
What makes you think that? Maybe there is something I'm missing.

Sorry for the delay in answer I was on holiday

**Comment by baek-b** [comment]
Any update on the above question? I'm not able to use two or more collections in the firebase extension either. It's only tracking the first one.

**Comment by bidoubiwa** [comment]
Hey @baek-b , I tried creating two instances of the extension on two different collection and it seems to work very well for me.

<img width="968" alt="Screenshot 2022-11-22 at 12 46 18" src="https://user-images.githubusercontent.com/33010418/203306331-7b34209e-1712-4e5a-a7b6-32d20422c384.png">

Obviously I understand you may be a bit afraid to add this directly into production, but as far as every test I made, there is no conflicts at all !

**Comment by bidoubiwa** [comment]
I'm closing this issue, if it still does not work feel free to re-open it!
